name: lr_obs
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.12,<=3.13.2
  - pip
  - qiskit>=1.4.0,<=1.4.2
  - matplotlib
  - notebook
  - numpy
  - pandas
  - tqdm
  - pylatexenc
  - msal
  - seaborn
  - scipy
  - pip:
    - qiskit-ibm-runtime>=0.37.0, <=0.37.0
    - qiskit-aer>=0.16.1, <=0.16.1
    - openpyxl>=3.1.4
